[build]
builder = "nixpacks"
buildCommand = "npm ci --legacy-peer-deps && npm run build"

[deploy]
startCommand = "node_modules/.bin/next start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
numReplicas = 1

[[deploy.ports]]
port = 3000
protocol = "TCP"
